version: '3.1'

services:

  db:
    image: postgres:12.3
    restart: always
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:6.0.5
    restart: always
    ports:
      - "6379:6379"
volumes:
  db_data:
